[package]
name = "discord-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
rand = "0.9.2"
reqwest = "0.12.24"
serenity = "0.12.4"
tokio = { version = "1.48.0", features = ["full"] }
